<a href="https://colab.research.google.com/github/prakhar00007/vector_db/blob/main/faiss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 27.9 MB/s eta 0:00:00


In [ ]:
import faiss
faiss.__version__

'1.13.1'

In [ ]:
bio_text = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.

The Entrepreneur and Teacher: Sudhanshu's Dual Legacy
Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching courses in Big Data, Data Science, or programming, Sudhanshu has always sought to make complex subjects accessible to learners at all levels.

His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds.

Th
e Journey

Early Life and the Power of Education

Rising Through the Ranks of the Tech World

The Birth of iNeuron: Democratizing Education

The Foundation of Euron: Expanding the Mission

Early Life and the Power of Education
Sudhanshu Kumar's life is a story of triumph over adversity, driven by the belief in the transformative power of education. Born in Jamshedpur, Jharkhand, India, to a family of very modest means, Sudhanshu's early years were marked by financial hardship. His surroundings offered little opportunity, and resources were limited, yet he understood from a young age that education could be his ticket out of poverty.

While many would have been daunted by the lack of support and opportunity, Sudhanshu was relentless in his pursuit of knowledge. He knew that education had the power to change lives, and he was determined to leverage it to create a better future for himself and his family. Despite the numerous challenges along the way, Sudhanshu excelled academically, eventually earning a degree in Computer Science and Engineering (CSE).
"""

In [ ]:
import requests
import os
import numpy as np
import json

In [ ]:
def chunk_text(text, chunk_size=10, overlap=2):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + chunk_size, len(words))
        chunk = ' '.join(words[start:end])
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

In [ ]:
chunks=chunk_text(bio_text)

In [ ]:
len(chunks)

49

In [ ]:
API_URL="https://api.euron.one/api/v1/euri/embeddings"
API_KEY="YOUR_API_KEY"
MODEL_NAME="text-embedding-3-small"

In [ ]:
header = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {API_KEY}"
}

In [ ]:
for i in enumerate(chunks):
  print(i)

(0, "Making an Impact Helping Millions of Students Succeed Sudhanshu's commitment")
(1, "Sudhanshu's commitment to affordable education wasn't just a business strategy—it")
(2, "business strategy—it was his life's mission. Over the years, iNeuron")
(3, 'years, iNeuron has helped over 1.5 million students from 34+')
(4, 'from 34+ countries, providing them with the skills they need')
(5, "they need to succeed in today's competitive job market. Many")
(6, 'market. Many of these students, like Sudhanshu himself, came from')
(7, 'came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an')
(8, 'a lifeline—an opportunity to rise above their circumstances. In 2022,')
(9, 'In 2022, iNeuron was acquired by PhysicsWallah in a deal')
(10, 'a deal worth ₹250 crore. While this acquisition was a')
(11, 'was a significant milestone, Sudhanshu remained focused on his mission.')
(12, 'his mission. Even after the acquisition, iNeuron continued to offer')
(13, 'to offer some of the most affor

In [ ]:
all_embeddings = []
for i ,chunk in enumerate(chunks):
    payload = {
        "model": MODEL_NAME,
        "input": chunk
    }
    response = requests.post(API_URL, headers=header, data=json.dumps(payload))
    data = response.json()
    embeddings = data['data'][0]['embedding']
    all_embeddings.append(embeddings)

    all_embeddings = []
for i ,chunk in enumerate(chunks):
    payload = {
        "model": MODEL_NAME,
        "input": chunk
    }
    response = requests.post(API_URL, headers=header, data=json.dumps(payload))
    data = response.json()
    embeddings = data['data'][0]['embedding']
    all_embeddings.append(embeddings)



In [ ]:
all_embeddings

[[0.013701986,
  -0.03450083,
  0.06028342,
  0.06559942,
  0.004900686,
  -0.02572943,
  -0.014765185,
  0.09340209,
  -0.03250733,
  -0.014951245,
  0.050342504,
  -0.02953037,
  -0.045425206,
  -0.0011072227,
  0.017835174,
  -0.0052528707,
  -0.028414011,
  -0.044601224,
  0.03330473,
  0.05613694,
  0.017011194,
  0.014233585,
  0.020081183,
  0.0077414224,
  0.055020582,
  -0.039869986,
  0.0062695555,
  -0.020214083,
  0.014393065,
  -0.05161834,
  -0.02817479,
  -0.02870639,
  -0.037584107,
  -0.004335861,
  0.00051166484,
  0.020373562,
  -0.046966843,
  0.019523004,
  0.0018290356,
  0.012266666,
  0.036308266,
  -0.004830913,
  0.023337232,
  0.020798843,
  -0.012339761,
  -0.0058775004,
  -0.047578182,
  0.005648248,
  0.0016039363,
  0.07208493,
  -0.02485229,
  0.040534485,
  0.047259223,
  -0.023510002,
  0.03495269,
  -0.012286601,
  0.0033656913,
  0.06145294,
  -0.063366696,
  -0.046701044,
  -0.009409317,
  0.0040235464,
  0.025157962,
  0.023270782,
  -0.017888334,


In [ ]:
len(all_embeddings)

49

In [ ]:
embeddings_array=np.array(all_embeddings,dtype=np.float32)

array([[ 0.01370199, -0.03450083,  0.06028342, ..., -0.00386407,
        -0.0038541 , -0.00483091],
       [-0.00270775,  0.02011846,  0.0172799 , ..., -0.00195887,
        -0.00337815, -0.00348607],
       [-0.00975724,  0.01606824, -0.00957996, ..., -0.01460749,
         0.00899141, -0.02998082],
       ...,
       [ 0.06206916,  0.01672514,  0.05411157, ..., -0.03160298,
        -0.05357159, -0.01242662],
       [-0.00824316, -0.0119251 ,  0.03206893, ..., -0.01180298,
         0.02073612, -0.00082279],
       [-0.00375096,  0.00632304,  0.03000767, ..., -0.06082506,
        -0.00288169,  0.01989794]], dtype=float32)

In [ ]:
base_index = faiss.IndexFlatL2(1536)

In [ ]:
base_index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7e373f4a9e30> >

In [ ]:
base_index.add(embeddings_array)

In [ ]:
base_index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7e373f4a9e30> >

In [ ]:
faiss.write_index(base_index, "faiss_index.faiss")

In [ ]:
query_test="tell me about sudhanshu kumar early life"

In [ ]:
def embedding_text(text):
    payload = {
        "model": MODEL_NAME,
        "input": text
    }
    response = requests.post(API_URL, headers=header, data=json.dumps(payload))
    data = response.json()
    embeddings = data['data'][0]['embedding']
    emb = np.array(embeddings,dtype="float32").reshape(1,-1)

    return emb

In [ ]:
embedding_text(query_text)

array([[-0.02084059, -0.03050023, -0.0025927 , ..., -0.00046188,
         0.02570133,  0.01086555]], dtype=float32)

In [ ]:
query_test_emb  = embedding_text(query_test)

In [ ]:
query_test_emb

array([[-0.02084059, -0.03050023, -0.0025927 , ..., -0.00046188,
         0.02570133,  0.01086555]], dtype=float32)

In [ ]:
base_index.search(query_test_emb,5)

(array([[0.84445083, 0.8751737 , 0.9346856 , 0.938421  , 0.9627028 ]],
       dtype=float32),
 array([[47, 32, 36, 42, 11]]))

In [ ]:
indices = np.array([[47, 32, 36, 42, 11]])

# Print the specific chunks
for idx in indices[0]:
    print(f"\n=== Chunk {idx} ===")
    print(chunks[idx])


=== Chunk 47 ===
along the way, Sudhanshu excelled academically, eventually earning a degree

=== Chunk 32 ===
Power of Education Sudhanshu Kumar's life is a story of

=== Chunk 36 ===
very modest means, Sudhanshu's early years were marked by financial

=== Chunk 42 ===
opportunity, Sudhanshu was relentless in his pursuit of knowledge. He

=== Chunk 11 ===
was a significant milestone, Sudhanshu remained focused on his mission.
